# Generated by Django 3.2.7 on 2021-12-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mark', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_no', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('subunit', models.CharField(max_length=20)),
                ('appointment', models.CharField(max_length=50)),
                ('unit_join_date', models.DateField(blank=True)),
                ('last_promotion_date', models.DateField(blank=True)),
                ('contact', models.CharField(max_length=50)),
                ('date_of_enrollment', models.DateField(blank=True)),
                ('previous_subunit', models.CharField(max_length=20)),
                ('due_date_of_next_rank', models.DateField(blank=True)),
                ('observations', models.ManyToManyField(to='core.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='SoldierReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date_from', models.DateField()),
                ('evaluation_date_to', models.DateField()),
                ('medical_category', models.CharField(max_length=1)),
                ('IPFT_first_biannual', models.PositiveIntegerField()),
                ('IPFT_second_biannual', models.PositiveIntegerField()),
                ('RET', models.PositiveBigIntegerField()),
                ('DIV_order_letter_no_1', models.CharField(max_length=100)),
                ('DIV_order_letter_no_2', models.CharField(max_length=100)),
                ('DIV_order_letter_no_3', models.CharField(max_length=100)),
                ('fit_for_next_promotion', models.PositiveIntegerField(blank=True)),
                ('fit_for_next_promotion_yes_text', models.CharField(blank=True, max_length=100)),
                ('fit_for_next_promotion_no_text', models.CharField(blank=True, max_length=100)),
                ('fit_for_being_instructor', models.PositiveIntegerField(blank=True)),
                ('fit_for_being_instructor_yes_text', models.CharField(blank=True, max_length=100)),
                ('fit_for_being_instructor_no_text', models.CharField(blank=True, max_length=100)),
                ('fit_for_foreign_mission', models.PositiveIntegerField(blank=True)),
                ('fit_for_foreign_mission_yes_text', models.CharField(blank=True, max_length=100)),
                ('fit_for_foreign_mission_no_text', models.CharField(blank=True, max_length=100)),
                ('recommendation_for_next_appt', models.CharField(blank=True, max_length=100)),
                ('special_quality', models.CharField(blank=True, max_length=100)),
                ('remarks_by_initiating_officer', models.CharField(blank=True, max_length=100)),
                ('grade', models.PositiveBigIntegerField()),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='SoldierMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=0)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soldier')),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcriteria')),
            ],
        ),
    ]
