# Generated by Django 3.2.7 on 2021-10-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_no', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('subunit', models.CharField(max_length=20)),
                ('appointment', models.CharField(max_length=50)),
                ('join_date', models.DateField(blank=True)),
                ('commision_date', models.DateField(blank=True)),
                ('contact', models.CharField(max_length=50)),
                ('previous_company', models.CharField(max_length=20)),
                ('mission', models.CharField(max_length=45)),
            ],
        ),
    ]
