# Generated by Django 3.2.7 on 2021-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriteria',
            name='company',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
