# Generated by Django 3.2.7 on 2021-11-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criteria_observation_subcriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcriteria',
            old_name='criteria_id',
            new_name='criteria',
        ),
        migrations.CreateModel(
            name='SoldierMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=0)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soldier')),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcriteria')),
            ],
        ),
    ]
