# Generated by Django 3.2.7 on 2022-01-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211231_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_category', models.CharField(max_length=1)),
                ('IPFT_first_biannual', models.BooleanField()),
                ('IPFT_second_biannual', models.BooleanField()),
                ('RET', models.BooleanField()),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.soldier')),
            ],
        ),
    ]
