# Generated by Django 3.2.7 on 2021-10-06 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_no', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('subunit', models.CharField(max_length=20)),
                ('starting_date', models.DateField(auto_now_add=True)),
                ('contact', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, default='army.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
