# Generated by Django 3.2.7 on 2021-10-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
